### ISSUE TITLE
Input `//` the first character is missing

### ISSUE THREAD

**Issue by heavenshell** [mityu/vim-wispath#4]
Hi, thank you for creating nice plugin. I love it.

I found some strange behavior.

When I type `//` and `<c-x><c-f>`, the first character is missing.

<img width="730" alt="スクリーンショット 2024-12-13 23 15 10" src="https://github.com/user-attachments/assets/39e5efad-513a-49d2-aa21-a00698dae5d7" />

Vim's default `<c-x><c-f>` result

<img width="731" alt="スクリーンショット 2024-12-13 23 23 56" src="https://github.com/user-attachments/assets/7304cc9d-d038-4dae-9285-2e1e613cc66c" />

Below is `getcompletion()` result and the first character is not missing.

```
:echomsg getcompletion('//', 'file')
['//Applications/', '//bin/', '//cores/', '//dev/', '//etc/', '//home/', '//Library/', '//opt/', '//private/', '//sbin/', '//System/', '//tmp/', '//Users/', '//usr/', '//var/', '//Volumes/']
```

Using MacVim with cli.
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Sep 11 2024 06:07:33)
macOS version - arm64
Included patches: 1-727
```

Thank you

**Comment by mityu** [comment]
Could you try #6 ?

**Comment by heavenshell** [comment]
Thank you for fixing this.
It works fine!

**Comment by mityu** [comment]
Thank you for your report.
